<?php

namespace Knp\ChallengeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Knp\ChallengeBundle\Entity\Game;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function existThisGame(Game $game)
    {
        if ($game->getHomeTeam()->getId() && $game->getAwayTeam()->getId()) {
            return $this->findOneBy(array(
                'homeTeam' => $game->getHomeTeam(),
                'awayTeam' => $game->getAwayTeam(),
                'date' => $game->getDate(),
            ));
        }
    }
}
