parameters:
#    challenge.example.class: Knp\ChallengeBundle\Example
    challenge.helper.class: Knp\ChallengeBundle\Helper

services:
#    challenge.example:
#        class: %challenge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    challenge.helper:
        class: %challenge.helper.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
