parameters:
#    challenge.example.class: Knp\ChallengeBundle\Example
    challenge.import_soccer_way.class: Knp\ChallengeBundle\ImportSoccerWay
    challenge.team_manager.class: Knp\ChallengeBundle\Manager\TeamManager

services:
#    challenge.example:
#        class: %challenge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    challenge.import_soccer_way:
        class: %challenge.import_soccer_way.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            teamManager: "@challenge.team_manager"

    challenge.team_manager:
        class: %challenge.team_manager.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
