parameters:
#    challenge.example.class: Knp\ChallengeBundle\Example
    challenge.import_soccer_way.class: Knp\ChallengeBundle\ImportSoccerWay
    challenge.team_manager.class: Knp\ChallengeBundle\Manager\TeamManager
    challenge.game_manager.class: Knp\ChallengeBundle\Manager\GameManager
    challenge.standings_manager.class: Knp\ChallengeBundle\Manager\StandingsManager

services:
#    challenge.example:
#        class: %challenge.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    challenge.import_soccer_way:
        class: %challenge.import_soccer_way.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            teamManager: "@challenge.team_manager"
            gameManager: "@challenge.game_manager"

    challenge.team_manager:
        class: %challenge.team_manager.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"

    challenge.game_manager:
            class: %challenge.game_manager.class%
            arguments:
                entityManager: "@doctrine.orm.entity_manager"

    challenge.standings_manager:
                class: %challenge.standings_manager.class%
                arguments:
                    entityManager: "@doctrine.orm.entity_manager"
